### ISSUE TITLE
Bird is not flying while touching

### ISSUE THREAD

**Issue by Tasmia-Intel** [m-peko/CrazyFlappyBird#1]
CCScheduler#schedule. Reiniting timer with interval 0.2500, repeat 4294967294, delay 0.0000-
getting this log in output window

**Comment by Tasmia-Intel** [comment]
Please help on this issue

**Comment by m-peko** [comment]
Can you please explain a bit more what have you done and what is the problem?

**Comment by m-peko** [comment]
Due to lack of details, I will close this issue. Feel free to reopen the issue once the details are provided.
